version: '3'
services:
  fg-app:
    container_name: fg-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '871:8000'
    volumes:
      - .:/app

  fg-db:
    container_name: fg-db
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: eSlS3cr3t
      POSTGRES_DB: fastgraph
    ports:
      - "873:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    # volumes:
      # - ./db:/docker-entrypoint-initdb.d
      # - db_data:/var/lib/mysql

  fg-pgadmin:
    image: dpage/pgadmin4
    container_name: fg-pgadmin
    restart: unless-stopped
    ports:
      - "872:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    depends_on:
      - fg-db
